spring:
  application:
    name: Prize_Drawing_System
  datasource:
    url: jdbc:postgresql://${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enabled: true

server:
  port: 8080

jwt:
  secret:
    access: ${JWT_ACCESS}
    refresh: ${JWT_REFRESH}